version: <docker-compose-version>
services:
database:
image: <database-docker-image-name>
ports:
- "<databasePort>:<databasePort>"
environment:
POSTGRES_USER: <databaseUser>
POSTGRES_PASSWORD: <databasePassword>
POSTGRES_DB:<databaseName>
<service-name>:
image: <service-docker-image-name>
ports:
- "<applicationPort>:<applicationPort>"
environment:
PROFILE: <profile-name>
DATABASESERVER_PORT: "<databasePort>"
container_name: <container_name>
networks:
backend:
aliases:
- "alias"
networks:
backend:
driver: bridge#stage 1
#Start with a base image containing Java runtime
FROM openjdk:11-slim as build
# Add Maintainer Info
LABEL maintainer="Illary Huaylupo <illaryhs@gmail.com>"
# The application's jar file
ARG JAR_FILE
# Add the application's jar to the container
COPY ${JAR_FILE} app.jar
#unpackage jar file
RUN mkdir -p target/dependency && (cd target/dependency; jar -xf /app.jar)
#stage 2
#B
#Same Java runtime
FROM openjdk:11-slim
#Add volume pointing to /tmp
